plugins:
  signatures_enabled:
    default: true
    client: true
  signatures_advanced_mode:
    default: false
    client: true
  signatures_visible_by_default:
    default: false
    client: true
  signatures_user_enabled_by_default:
    default: true
    client: true
  signatures_links_open_in_new_tab:
    default: false
    client: true
